"use client";

import Link from "next/link";

export default function TermsOfService() {
  const lastUpdated = "August 12, 2026";

  return (
    <main className="min-h-screen bg-white">
      {/* Header */}
      <div className="border-b border-slate-200">
        <div className="mx-auto max-w-4xl px-6 py-12">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900 transition-colors mb-8"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="m15 18-6-6 6-6"/>
            </svg>
            Back to ShipSync AI
          </Link>
          <h1 className="text-4xl font-bold tracking-tight text-slate-900">Terms of Service</h1>
          <p className="mt-3 text-slate-500">Last updated: {lastUpdated}</p>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="prose prose-slate max-w-none">

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-10">
            <p className="text-sm text-amber-800 m-0 font-medium">
              ⚠️ Legal Notice: These Terms of Service govern your use of ShipSync AI's platform, AI models, and export compliance tools. They are drafted considering the Information Technology Act, 2000, Indian Contract Act, 1872, and applicable export control regulations. Please have these reviewed by legal counsel before publication.
            </p>
          </div>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">1. Definitions</h2>
            <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 space-y-3">
              <p className="text-slate-700 m-0"><strong>"Platform" / "Services"</strong> means the ShipSync AI web application, APIs, AI models, document generation tools, HS code classifiers, and all related export compliance features accessible via shipsync.ai or associated domains.</p>
              <p className="text-slate-700 m-0"><strong>"User" / "You"</strong> means any individual or entity accessing or using the Services, including exporters, customs brokers, CHAs, logistics providers, and enterprise clients.</p>
              <p className="text-slate-700 m-0"><strong>"AI Models"</strong> means our proprietary and third-party machine learning models, large language models (LLMs), and algorithms used for HS code classification, document generation, route optimization, and compliance analysis.</p>
              <p className="text-slate-700 m-0"><strong>"Output"</strong> means any content generated by our AI Models, including but not limited to HS code suggestions, duty calculations, document drafts, compliance recommendations, and risk assessments.</p>
              <p className="text-slate-700 m-0"><strong>"Input"</strong> means any data, documents, product descriptions, or queries you submit to the Platform for processing.</p>
              <p className="text-slate-700 m-0"><strong>"Regulatory Authorities"</strong> means DGFT, Customs Department (CBIC), RBI, FEMA authorities, and any other Indian government body with jurisdiction over export activities.</p>
            </div>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">2. Acceptance of Terms</h2>
            <p className="text-slate-600 leading-relaxed">
              By accessing, registering for, or using ShipSync AI, you agree to be bound by these Terms of Service, our Privacy Policy, and all applicable laws and regulations. If you are using the Services on behalf of a company or other legal entity, you represent that you have the authority to bind such entity to these Terms. If you do not agree to these Terms, you must not access or use the Services.
            </p>
            <p className="text-slate-600 leading-relaxed mt-3">
              We reserve the right to modify these Terms at any time. Material changes will be notified via email or platform notification at least 7 days before taking effect. Continued use after such changes constitutes acceptance.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">3. Eligibility & Account Registration</h2>
            <p className="text-slate-600 leading-relaxed">
              You must be at least 18 years old and capable of entering into a legally binding contract under the Indian Contract Act, 1872. To use certain features, you must register an account and provide accurate, current, and complete information, including:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>Valid Import Export Code (IEC) issued by DGFT (where required for specific features)</li>
              <li>GSTIN and PAN (for invoice generation and tax compliance features)</li>
              <li>Accurate business and contact information</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized access or security breach.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">4. Description of Services</h2>
            <p className="text-slate-600 leading-relaxed">
              ShipSync AI provides AI-powered tools to assist Indian exporters with compliance workflows. Our Services include:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li><strong>AI HS Code Classifier:</strong> Suggests 8-digit Harmonized System codes based on product descriptions and technical specifications.</li>
              <li><strong>Auto Document Generator:</strong> Creates draft commercial invoices, packing lists, shipping bills, and other export documents formatted for ICEGATE submission.</li>
              <li><strong>DGFT Benefit Finder:</strong> Identifies applicable RoDTEP, MEIS, and FTA benefits based on your product and destination data.</li>
              <li><strong>FTA Route Optimizer:</strong> Recommends trade routes and certificate requirements under India's Free Trade Agreements.</li>
              <li><strong>Document Validator:</strong> Checks for mismatches between invoice, packing list, and shipping bill data.</li>
              <li><strong>Compliance Dashboard:</strong> Provides a consolidated view of shipments, benefits claimed, and compliance status.</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              <strong>Important:</strong> ShipSync AI is a software tool designed to assist with export compliance. It does not replace licensed customs brokers, chartered accountants, or legal advisors. We are not a customs house agent (CHA) and do not file documents on your behalf with ICEGATE, DGFT, or customs authorities unless explicitly stated in a separate service agreement.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">5. User Obligations & Representations</h2>
            <p className="text-slate-600 leading-relaxed mb-4">
              By using our Services, you represent, warrant, and covenant that:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-2">
              <li>You hold all necessary licenses, registrations, and approvals required for your export activities under the Foreign Trade (Development & Regulation) Act, 1992, FTP 2023, and other applicable laws.</li>
              <li>You possess a valid IEC from DGFT and all required RCMC registrations.</li>
              <li>All Input data (product descriptions, documents, specifications) provided by you is accurate, complete, and lawfully obtained. You have the right to share this data with us.</li>
              <li>You will not use the Platform for any illegal, fraudulent, or unauthorized export activities, including exports prohibited under India's Special Chemicals, Organisms, Materials, Equipment and Technologies (SCOMET) list or UN sanctions.</li>
              <li>You will not attempt to reverse-engineer, scrape, or extract our AI Models, training data, or proprietary algorithms.</li>
              <li>You will not upload malware, viruses, or any code designed to disrupt the Platform.</li>
              <li>You will not use automated scripts, bots, or scrapers to access the Services without our written consent.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">6. AI-Generated Content Disclaimer & Limitations</h2>
            <div className="bg-red-50 border border-red-200 rounded-xl p-6 mb-6">
              <h3 className="text-red-900 font-semibold mb-2">⚠️ CRITICAL DISCLAIMER — READ CAREFULLY</h3>
              <p className="text-red-800 text-sm leading-relaxed m-0">
                ShipSync AI's Outputs are generated by artificial intelligence models and are provided for <strong>assistance and informational purposes only</strong>. They do not constitute legal, tax, customs, or regulatory advice. You must independently verify all Outputs with qualified professionals before relying on them for actual export filings.
              </p>
            </div>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">6.1 HS Code Classification</h3>
            <p className="text-slate-600 leading-relaxed">
              Our AI HS Code Classifier suggests codes based on product descriptions and historical data. However:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>HS code classification requires expert judgment and may depend on factors not captured in your Input (material composition, end-use, manufacturing process).</li>
              <li>Customs authorities may classify products differently from our AI suggestions.</li>
              <li>Wrong HS codes can result in customs penalties, duty demands, shipment delays, seizure of goods, and legal proceedings.</li>
              <li>You are solely responsible for confirming the final HS code with a licensed CHA or customs authority before filing.</li>
            </ul>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">6.2 Document Generation</h3>
            <p className="text-slate-600 leading-relaxed">
              AI-generated documents (invoices, packing lists, shipping bills) are drafts requiring human review. You must verify:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>Accuracy of quantities, values, weights, and dimensions</li>
              <li>Correctness of buyer/seller details and bank information</li>
              <li>Compliance with Letter of Credit (L/C) terms, if applicable</li>
              <li>Alignment with actual physical shipment details</li>
            </ul>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">6.3 DGFT Benefit & FTA Recommendations</h3>
            <p className="text-slate-600 leading-relaxed">
              Our benefit finder analyzes publicly available DGFT notifications and FTA texts. However, eligibility for RoDTEP, MEIS, or FTA benefits depends on specific conditions (Rules of Origin, value addition thresholds, direct consignment rules) that may not be fully captured by our AI. You must verify benefit eligibility with DGFT, EPCs, or your CHA before claiming.
            </p>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">6.4 No Liability for AI Errors</h3>
            <p className="text-slate-600 leading-relaxed">
              To the maximum extent permitted by law, ShipSync AI and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your reliance on AI-generated Outputs, including but not limited to customs penalties, duty demands, shipment delays, loss of business, or reputational harm.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">7. Intellectual Property Rights</h2>
            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">7.1 Our IP</h3>
            <p className="text-slate-600 leading-relaxed">
              ShipSync AI retains all rights, title, and interest in and to the Platform, AI Models, software, algorithms, databases, trademarks, logos, and all underlying technology. These Terms do not grant you any license to our patents, copyrights, trade secrets, or trademarks except as necessary to use the Services.
            </p>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">7.2 Your IP & Inputs</h3>
            <p className="text-slate-600 leading-relaxed">
              You retain ownership of your Input data, product catalogs, and business information. By submitting Input to the Platform, you grant us a limited, non-exclusive, royalty-free license to use, process, store, and analyze such data solely to provide and improve the Services.
            </p>

            <h3 className="text-lg font-semibold text-slate-900 mt-6 mb-2">7.3 AI Output Ownership</h3>
            <p className="text-slate-600 leading-relaxed">
              Subject to your compliance with these Terms and payment of applicable fees, we assign to you all rights, title, and interest in AI-generated Outputs (documents, code suggestions, reports) created specifically for you. However, we retain the right to use anonymized, aggregated Outputs for model training and service improvement, provided such use does not identify you or your business.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">8. Subscription, Payment & Refunds</h2>
            <p className="text-slate-600 leading-relaxed">
              Certain features of ShipSync AI may require payment of subscription fees or per-transaction charges. All fees are exclusive of applicable GST and other taxes. Payment terms:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>Fees are charged in advance for subscription plans or post-usage for pay-as-you-go features.</li>
              <li>Failure to pay may result in suspension or termination of your account.</li>
              <li>Refunds are provided only for service outages exceeding 24 hours attributable to our infrastructure, or as required by consumer protection laws.</li>
              <li>Price changes will be notified 30 days in advance.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">9. Data Accuracy & Regulatory Compliance</h2>
            <p className="text-slate-600 leading-relaxed">
              You are solely responsible for ensuring that:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-2 mt-2">
              <li>All export documents generated or validated through our Platform accurately reflect the actual physical shipment.</li>
              <li>You comply with the Foreign Trade Policy, Customs Act, 1962, FEMA, 1999, and all applicable export control regulations.</li>
              <li>You obtain necessary export licenses for restricted, prohibited, or SCOMET items.</li>
              <li>You do not misdeclare product descriptions, values, or origins to obtain incorrect HS codes or duty benefits.</li>
              <li>You maintain proper records as required by DGFT and CBIC for audit and verification purposes.</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-4">
              ShipSync AI is not responsible for verifying your export license status, SCOMET applicability, or end-user credentials. These remain your exclusive responsibility.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">10. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              To the fullest extent permitted by applicable law:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-2 mt-2">
              <li>ShipSync AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, lost data, business interruption, or reputational harm.</li>
              <li>Our total aggregate liability for any claim arising from these Terms or the Services shall not exceed the total amount paid by you to ShipSync AI in the 12 months preceding the claim, or ₹10,000 (Indian Rupees Ten Thousand), whichever is higher.</li>
              <li>We are not liable for damages arising from: (a) your misuse of the Services; (b) unauthorized access to your account due to your negligence; (c) actions or omissions of Regulatory Authorities; (d) force majeure events; (e) third-party services or integrations (ICEGATE, banking portals).</li>
              <li>We are not liable for customs penalties, duty demands, shipment seizures, or any regulatory action taken against you based on AI-generated Outputs or your use of the Platform.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">11. Indemnification</h2>
            <p className="text-slate-600 leading-relaxed">
              You agree to indemnify, defend, and hold harmless ShipSync AI, its directors, officers, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising from:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>Your violation of these Terms or any applicable law</li>
              <li>Your misuse of AI-generated Outputs for actual export filings without independent verification</li>
              <li>Any export control violation, misdeclaration, or fraud committed by you</li>
              <li>Your infringement of any third-party intellectual property rights</li>
              <li>Any dispute between you and a customs broker, buyer, bank, or Regulatory Authority</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">12. Termination</h2>
            <p className="text-slate-600 leading-relaxed">
              We may suspend or terminate your account immediately, without prior notice, if:
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li>You violate any provision of these Terms</li>
              <li>You engage in fraudulent, illegal, or unauthorized export activities</li>
              <li>Your payment is overdue by more than 30 days</li>
              <li>Required by law or order of a Regulatory Authority</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              Upon termination, your right to use the Services ceases immediately. We may retain your data as required by law or as described in our Privacy Policy. Provisions regarding IP, liability, indemnification, and governing law shall survive termination.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">13. Third-Party Integrations & Services</h2>
            <p className="text-slate-600 leading-relaxed">
              The Platform may integrate with or link to third-party services, including ICEGATE, DGFT portals, payment gateways, and cloud storage providers. Your use of such third-party services is governed by their respective terms and privacy policies. ShipSync AI does not control and is not responsible for the content, security, or availability of third-party services. We do not guarantee uninterrupted ICEGATE connectivity or real-time DGFT data accuracy.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">14. Governing Law & Jurisdiction</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles. Any dispute arising from these Terms or the Services shall be subject to the exclusive jurisdiction of the courts at [Your City], India.
            </p>
            <p className="text-slate-600 leading-relaxed mt-3">
              Before initiating litigation, you agree to attempt to resolve disputes informally by contacting us at legal@shipsync.ai. If not resolved within 30 days, either party may pursue formal remedies. Nothing in these Terms prevents either party from seeking injunctive relief in a court of competent jurisdiction.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">15. Dispute Resolution & Arbitration</h2>
            <p className="text-slate-600 leading-relaxed">
              Any dispute, controversy, or claim arising out of or relating to these Terms, including their formation, interpretation, breach, termination, or validity, shall be resolved through arbitration administered by the [Arbitration Institution, e.g., Delhi International Arbitration Centre] in accordance with the Arbitration and Conciliation Act, 1996.
            </p>
            <ul className="list-disc pl-6 text-slate-600 space-y-1 mt-2">
              <li><strong>Seat:</strong> [Your City], India</li>
              <li><strong>Language:</strong> English</li>
              <li><strong>Arbitrators:</strong> Sole arbitrator appointed mutually; failing agreement, by the arbitration institution</li>
              <li><strong>Cost:</strong> Each party bears its own costs; arbitrator fees shared equally unless otherwise awarded</li>
            </ul>
            <p className="text-slate-600 leading-relaxed mt-3">
              Notwithstanding the above, either party may approach a competent court for interim or urgent relief.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">16. Force Majeure</h2>
            <p className="text-slate-600 leading-relaxed">
              ShipSync AI shall not be liable for any failure or delay in performing our obligations due to causes beyond our reasonable control, including but not limited to: acts of God, natural disasters, wars, terrorism, riots, government actions, internet outages, cyberattacks, strikes, or failures of third-party infrastructure providers.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">17. Severability</h2>
            <p className="text-slate-600 leading-relaxed">
              If any provision of these Terms is held invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be modified to the minimum extent necessary to make it enforceable, or if not possible, severed from these Terms. The remaining provisions shall continue in full force and effect.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">18. Waiver</h2>
            <p className="text-slate-600 leading-relaxed">
              No waiver of any provision of these Terms shall be effective unless in writing signed by the waiving party. Our failure to enforce any right or provision shall not constitute a waiver of such right or provision.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">19. Entire Agreement</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms, together with our Privacy Policy, Cookie Policy, and any additional service-specific terms you agree to, constitute the entire agreement between you and ShipSync AI regarding the Services and supersede all prior agreements, understandings, and communications.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">20. Contact Information</h2>
            <div className="bg-slate-900 text-white rounded-xl p-8">
              <p className="text-slate-300 leading-relaxed">
                For legal notices, questions about these Terms, or to report violations, contact:
              </p>
              <div className="mt-6 space-y-3">
                <p className="m-0"><strong className="text-white">Legal Department</strong></p>
                <p className="text-slate-300 m-0">Email: legal@shipsync.ai</p>
                <p className="text-slate-300 m-0">Address: [Your Registered Office Address]</p>
                <p className="text-slate-400 text-sm mt-4 m-0">Response time: Within 48 hours for legal inquiries.</p>
              </div>
            </div>
          </section>

        </div>
      </div>
    </main>
  );
}
